version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image:  <username/repo:tag>
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "4000:8080"
    networks:
      - webnet
networks:
  webnet: